CREATE TABLE EMP (
    EMPNO NUMBER(6),
    ENAME VARCHAR2(20) NOT NULL,
    JOB VARCHAR2(10) NOT NULL,
    MGR NUMBER(4),
    DEPTNO NUMBER(3),
    SAL NUMBER(7,2)
);

ALTER TABLE EMP ADD COMMISSION NUMBER;

ALTER TABLE EMP MODIFY JOB VARCHAR2(20);

CREATE TABLE DEPT (
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(10),
    LOC VARCHAR2(10)
);

ALTER TABLE EMP ADD CONSTRAINT PK_EMPNO PRIMARY KEY (EMPNO);
ALTER TABLE EMP ADD CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO);

ALTER TABLE EMP ADD CONSTRAINT CHK_EMPNO CHECK (EMPNO > 100);

ALTER TABLE EMP MODIFY SAL DEFAULT 5000;

ALTER TABLE EMP ADD DOB DATE;

