1.1  
SQL> CREATE TABLE TANMOYEMP(
  2  EMPNO NUMBER(6),
  3  ENAME VARCHAR2(20) NOT NULL,
  4  JOB VARCHAR2(10) NOT NULL,
  5  MGR NUMBER(4),
  6  DEPTNO NUMBER(3),
  7  SAL NUMBER(7, 2)
  8  );
Table created.

1.2
SQL> ALTER TABLE TANMOYEMP ADD COMMISSION NUMBER;
Table altered.

1.3
SQL> ALTER TABLE TANMOYEMP MODIFY JOB VARCHAR2(20);
Table altered.

1.4
SQL> CREATE TABLE TANMOYDEPT(
  2  DEPTNO NUMBER(2) PRIMARY KEY,
  3  DNAME VARCHAR2(10),
  4  LOC VARCHAR2(10)
  5  );
Table created.

1.5
SQL> ALTER TABLE TANMOYEMP ADD CONSTRAINT TAN_PK_EMPNO PRIMARY KEY (EMPNO);
Table altered.
SQL> ALTER TABLE TANMOYEMP ADD CONSTRAINT TAN_FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO);
Table altered.

1.6
SQL> ALTER TABLE TANMOYEMP ADD CONSTRAINT TAN_CHK_EMPNO CHECK (EMPNO > 100);
Table altered.

1.7
SQL> ALTER TABLE TANMOYEMP MODIFY SAL DEFAULT 5000;
Table altered.

1.8
SQL> ALTER TABLE TANMOYEMP ADD DOB DATE;
Table altered.

