INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES (30, 'SALES', 'CHICAGO');

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (101, 'SMITH', 'CLERK', 100, 20, 800, NULL, TO_DATE('1990-01-01', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (102, 'ALLEN', 'SALESMAN', 101, 30, 1600, 300, TO_DATE('1985-06-15', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (103, 'WARD', 'SALESMAN', 102, 30, 1250, 500, TO_DATE('1983-09-25', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (104, 'JONES', 'MANAGER', 105, 20, 2975, NULL, TO_DATE('1979-03-28', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (105, 'BLAKE', 'MANAGER', 106, 30, 2850, NULL, TO_DATE('1978-05-01', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (106, 'CLARK', 'MANAGER', 107, 10, 2450, NULL, TO_DATE('1976-11-17', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (107, 'SCOTT', 'ANALYST', 104, 20, 3000, NULL, TO_DATE('1981-12-09', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (108, 'TURNER', 'SALESMAN', 105, 30, 1500, 0, TO_DATE('1983-08-21', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (109, 'ADAMS', 'CLERK', 107, 20, 1100, NULL, TO_DATE('1985-04-03', 'YYYY-MM-DD'));
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, DEPTNO, SAL, COMMISSION, DOB) 
VALUES (110, 'MILLER', 'CLERK', 106, 10, 1300, NULL, TO_DATE('1982-01-21', 'YYYY-MM-DD'));

UPDATE EMP 
SET COMMISSION = 1000 
WHERE JOB = 'MANAGER';

CREATE TABLE EMPLOYEE AS SELECT * FROM EMP;

DELETE FROM EMP 
WHERE JOB = 'SUPERVISOR';

DELETE FROM EMP 
WHERE EMPNO = 7599;

SELECT * FROM EMP 
ORDER BY SAL ASC;

SELECT * FROM EMP 
ORDER BY SAL DESC;

SELECT * FROM EMP 
WHERE DEPTNO = 30;

SELECT DISTINCT DEPTNO 
FROM EMPLOYEE;

SELECT * FROM EMP 
ORDER BY ENAME ASC;

CREATE TABLE MANAGER AS 
SELECT * FROM EMP 
WHERE JOB = 'MANAGER';

SELECT ENAME 
FROM EMP 
WHERE COMMISSION IS NULL;

SELECT E.ENAME, D.DNAME 
FROM EMP E 
JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO;
